### ISSUE TITLE
Show supported modes for connectors

### ISSUE THREAD

**Issue by ahartmetz** [ascent12/drm_info#1]
The graph presentation of drm_info is nice. However, when I also need to look at the supported modes (resolutions), this tool doesn't do it. It would be nice to display modes similar to that other tool:
https://git.kraxel.org/cgit/drminfo/
whose relevant part of the output looks like this:
```
HDMIA-1 (#28), connected
    encoder: TMDS (#27), active, crtc #67, fb #104, 1920x1080
    mode: 1920x1080 (6x)
    mode: 1680x1050
    mode: 1280x1024 (2x)
    mode: 1440x900 (2x)
    mode: 1280x960
    mode: 1152x864
    mode: 1280x720 (3x)
    mode: 1440x576
    mode: 1024x768 (3x)
    mode: 800x600 (3x)
    mode: 720x576
    mode: 720x480 (2x)
    mode: 640x480 (4x)
    mode: 720x400
```
It would be nice to also display other attributes of the modes, such as refresh rate. But resolutions are most important.

**Comment by ascent12** [comment]
Done

**Comment by ahartmetz** [comment]
Thanks a lot!
