### ISSUE TITLE
Add CI to make sure we don't break build on old libdrm

### ISSUE THREAD

**Issue by emersion** [ascent12/drm_info#12]
A CI service like builds.sr.ht could be wired up with the oldest platform we want to target to make sure we don't break builds there.

**Comment by emersion** [comment]
Wrote a very small builds.sr.ht manifest for debian/stretch: https://builds.sr.ht/~emersion/job/17090

If you're interested, webhooks can be set up to build commits and pull requests on GitHub.

**Comment by emersion** [comment]
Hmm, I think we just broke debian/stable, because it doesn't have json-c 0.13.

**Comment by ascent12** [comment]
Yeah, that's something I noticed too. They don't even have 0.13 in testing...
But I was writing a meson wrap file for json-c to get around this dumb situation.

I need to go through a few of the libdrm defines too.
