### ISSUE TITLE
Target Debian Buster

### ISSUE THREAD

**Issue by ascent12** [ascent12/drm_info#35]
I'm still sticking with the "target Debian stable" thing, and with a newly released stable, that should now be considered the minimum that's going to be supported.

Basically this just consists of bumping some minimum versions and removing some now unneeded compatibility defines.

**Comment by ascent12** [comment]
Also, we may want to wait for builds.sh.rt to update their Debian images before doing this.

**Comment by ddevault** [comment]
On builds.sr.ht, `debian/stable` now refers to buster, and `debian/testing` now refers to bullseye.

**Comment by emersion** [comment]
Successful sr.ht build with Buster: https://builds.sr.ht/~emersion/job/74308

Buster has libdrm 2.4.97.
