### ISSUE TITLE
Current display mode?

### ISSUE THREAD

**Issue by shmerl** [ascent12/drm_info#81]
Is there some way to see the current display mode, something similar to how xrandr indicates it:

```
  2560x1440 (0x5c) 768.500MHz +HSync -VSync *current
        h: width  2560 start 2608 end 2640 total 2720 skew    0 clock 282.54KHz
        v: height 1440 start 1443 end 1448 total 1570           clock 179.96Hz
```

I can see the list of modes in the JSON output, but couldn't figure out what's the current one.

Also, it would be nice to see details like above (i.e. sync pulses and porches) in the pretty output, not only in JSON one.

**Comment by emersion** [comment]
The current mode should be displayed in the CRTC, not the connector.

**Comment by shmerl** [comment]
Thanks for the pointer, I see it there!
